import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import Link from "next/link";
import { buildClasses } from "@/helpers/common.helper";
import { links } from "@/constants/common.constants";
import "./globals.css";

const rubik = Rubik({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en">
      <body
        className={buildClasses(
          rubik.className,
          `bg-white pl-32 pt-11 text-black`,
        )}
      >
        <div className="mr-32 flex flex-row items-center justify-between">
          <p className="text-base">A+ Studio</p>

          {/* nav link */}
          <ul className="flex flex-row gap-x-16">
            {links.map((link) => (
              <li key={link.text}>
                <Link href={link.href}>{link.text}</Link>
              </li>
            ))}
          </ul>
        </div>

        {/* content */}
        <div className="mt-10">{children}</div>
      </body>
    </html>
  );
};

export default RootLayout;
